### ISSUE TITLE
The "Twitter,YouTube,Medium,Discord" has not yet added

### ISSUE THREAD

**Issue by Tibinsunny** [developers-wtf/landingpage#2]
The usernames for the Twitter,YouTube,Medium,Discord has not yet added.Any user can go to these social medias and register the name "developers-wtf" and put their content there{when admin plans to register the username, it wont be avilable}.It is always a good practice to own all the usernames including the gmail before someone else does that.

Eg: Anyone could easily take https://twitter.com/developers-wtf as it  is not registered yet

Regards 
Tibin Sunny

**Comment by rivetin** [comment]
> The usernames for the Twitter,YouTube,Medium,Discord has not yet added.Any user can go to these social medias and register the name "developers-wtf" and put their content there{when admin plans to register the username, it wont be avilable}.It is always a good practice to own all the usernames including the gmail before someone else does that.
> 
> Eg: Anyone could easily take https://twitter.com/developers-wtf as it is not registered yet
> 
> Regards
> Tibin Sunny

Thank you so much for your concern please check https://twitter.com/developers.wtf

**Comment by Tibinsunny** [comment]
Looks like the issue is fixed...Hmm now you can close the issue

**Comment by hhsecond** [comment]
@ATHULBABYKURIAN The twitter link is apparently broken?

**Comment by Tibinsunny** [comment]
@ATHULBABYKURIAN  yes looks like the link is down....

**Comment by rivetin** [comment]
@hhsecond  https://twitter.com/DevelopersWtf

**Comment by Tibinsunny** [comment]
Yah now it looks fine...
